In [1]:
import numpy as np
import pandas as pd
from scipy import sparse

Creating Vector

In [2]:
#create vector as row
vector_row = np.array([1,2,3])
#create vector as column
vector_column = np.array([[1],[2],[3]])
print(vector_row,'\n', vector_column)

[1 2 3] 
 [[1]
 [2]
 [3]]


Creating Matrix

In [3]:
#creating matrix
matrix = np.array([[1,2],
[1,2],
[1,2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

Creating a Sparse Matrix

In [4]:
matrix1 = np.array([[0,0],
[0,1],
[3,0]])

#Create compressed sparse row
#show index matrix where value notzero
matrix_sparse = sparse.csr_matrix(matrix1)
print(matrix1,'\n',matrix_sparse)

[[0 0]
 [0 1]
 [3 0]] 
   (1, 1)	1
  (2, 0)	3


In [5]:
#Create large matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
#Create compressed sparse row(CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


Selecting Elements

In [22]:
#Create row vector
vector = np.array([1,2,3,4,5,6])
#Create matrix
matrix = np.array([[1,2,3],
[4,5,6],
[7,8,9]])
# Select the first two rows and all columns of a matrix
matrix[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# Select all rows and the second column
matrix[:,1:2]


array([[-1],
       [ 3]])

Flattening a matrix

In [8]:
#Create matrix
matrix = np.array([[1,2,3],
[4,5,6],
[7,8,9]])
#Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#alternative simply
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

Finding the Rank of a Matrix <br/><br/>
if determinant < 0 then matrix rank 3

In [10]:
# Create matrix
matrix = np.array([[1, 1, 1],
 [1, 1, 10],
 [1, 1, 15]])

determinant = np.linalg.det(matrix)
matrix_rank = np.linalg.matrix_rank(matrix)

In [11]:
print(matrix_rank,'\n', determinant)

2 
 0.0


Calculating the Determinant

In [12]:
matrix = np.array([[1, 2, 3],
 [2, 4, 6],
 [3, 8, 9]])

np.linalg.det(matrix)

0.0

Finding Eigenvalues and Eigenvectors

In [13]:
'''A.x1 = Lambda.x1'''
matrix = np.array([[2,-1],[0,3]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print('lambda atau eigenvalue: ',eigenvalues)
print('eigenvector', eigenvectors)

lambda atau eigenvalue:  [2. 3.]
eigenvector [[ 1.         -0.70710678]
 [ 0.          0.70710678]]
