In [11]:
import numpy as np
import pandas as pd
from scipy import sparse

Creating Vector

In [4]:
#create vector as row
vector_row = np.array([1,2,3])
#create vector as column
vector_column = np.array([[1],[2],[3]])
print(vector_row,'\n', vector_column)

[1 2 3] 
 [[1]
 [2]
 [3]]


Creating Matrix

In [18]:
#creating matrix
matrix = np.array([[1,2],
[1,2],
[1,2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

Creating a Sparse Matrix

In [23]:
matrix1 = np.array([[0,0],
[0,1],
[3,0]])

#Create compressed sparse row
#show index matrix where value notzero
matrix_sparse = sparse.csr_matrix(matrix1)
print(matrix1,'\n',matrix_sparse)

[[0 0]
 [0 1]
 [3 0]] 
   (1, 1)	1
  (2, 0)	3


In [26]:
#Create large matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
#Create compressed sparse row(CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


Selecting Elements

In [42]:
#Create row vector
vector = np.array([1,2,3,4,5,6])
#Create matrix
matrix = np.array([[1,2,3],
[4,5,6],
[7,8,9]])
print(vector[2],' ',matrix[1,1])
# Select the first two rows and all columns of a matrix
matrix[:2,:]

3   5


array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
# Select all rows and the second column
matrix[:,1:2]


array([[2],
       [5],
       [8]])

Flattening a matrix

In [47]:
#Create matrix
matrix = np.array([[1,2,3],
[4,5,6],
[7,8,9]])
#Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
#alternative simply
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

Finding the Rank of a Matrix <br/><br/>
if determinant < 0 then matrix rank 3

In [64]:
# Create matrix
matrix = np.array([[1, 1, 1],
 [1, 1, 10],
 [1, 1, 15]])

determinant = np.linalg.det(matrix)
matrix_rank = np.linalg.matrix_rank(matrix)

In [66]:
print(matrix_rank,'\n', determinant)

2 
 0.0


Calculating the Determinant

In [68]:
matrix = np.array([[1, 2, 3],
 [2, 4, 6],
 [3, 8, 9]])

np.linalg.det(matrix)

0.0

In [ ]:
#page 13